keep-starknet-strange/shinigami

.github/workflows/check.yml
README.md

fix: Repo formatting

---

src/compiler.cairo
src/opcodes/opcodes.cairo
src/opcodes/tests/test_opcodes.cairo

feat: op_MAX implementation

---

src/compiler.cairo
src/opcodes/opcodes.cairo
src/opcodes/tests/test_opcodes.cairo

feat: op_1add impl

---

src/compiler.cairo
src/cond_stack.cairo
src/engine.cairo
src/lib.cairo
src/opcodes/opcodes.cairo
src/opcodes/tests/test_opcodes.cairo
src/stack.cairo

Implement the branchnig opcodes, like OP_IF, OP_ENDIF, OP_ELSE, and OP_NOTIF

feat: Branching opcodes

---

src/compiler.cairo
src/opcodes/opcodes.cairo
src/opcodes/tests/test_opcodes.cairo

feat: OP_LESSTHANOREQUAL impl

---

src/compiler.cairo
src/opcodes/opcodes.cairo

Note: The test for OP_FROMALTSTACK has yet to be included.

implement opcode fromaltstack

---

src/compiler.cairo
src/opcodes/opcodes.cairo
src/opcodes/tests/test_opcodes.cairo

Implemented code for opcode within

OPCODE_WITHIN

---

src/compiler.cairo
src/opcodes/opcodes.cairo
src/opcodes/tests/test_opcodes.cairo

Implemented code for opcode 1 negate that number -1 is pushed onto the stack.

opcode1negate push -1 on to the stack

---

src/compiler.cairo
src/opcodes/opcodes.cairo
src/opcodes/tests/test_opcodes.cairo

Implemented code for opcode booland

OP_BOOLAND

---

src/compiler.cairo
src/opcodes/opcodes.cairo
src/opcodes/tests/test_opcodes.cairo

feat: OP_GREATERTHANOREQUAL

---

src/compiler.cairo
src/opcodes/opcodes.cairo
src/opcodes/tests/test_opcodes.cairo

adding op_numequal

---

src/compiler.cairo
src/opcodes/opcodes.cairo
src/opcodes/tests/test_opcodes.cairo

adding op_toaltstack

---

src/compiler.cairo
src/opcodes/opcodes.cairo
src/opcodes/tests/test_opcodes.cairo

adding op_verify

---

src/compiler.cairo
src/opcodes/opcodes.cairo
src/opcodes/tests/test_opcodes.cairo

feat: implement op-boolor

---

src/compiler.cairo
src/opcodes/opcodes.cairo
src/opcodes/tests/test_opcodes.cairo
src/stack.cairo

Implement opcode tuck
resolves #59

feat: implement opcode tuck

---

src/compiler.cairo
src/opcodes/opcodes.cairo
src/opcodes/tests/test_opcodes.cairo

This PR implementation for OP_RESERVED1, OP_RESERVED2 and OP_VER

feat:implement OP_RESERVED1, OP_RESERVED2 and OP_VER 

---

src/opcodes/arithmetic.cairo
src/opcodes/bitwise.cairo
src/stack.cairo

Optimize gas usage by replacing unnecessary push_int with push_bool, -100000 gas per opcode call

dev: refactor push_int with push_bool

---

.all-contributorsrc
README.md

Dev: contributors and acknowledgements

---

src/compiler.cairo
src/opcodes/opcodes.cairo
src/opcodes/stack.cairo
src/opcodes/tests/test_stack.cairo
src/scriptnum/scriptnum.cairo
src/stack.cairo

feat: op_pick opcode

---

src/compiler.cairo
src/errors.cairo
src/opcodes/opcodes.cairo
src/opcodes/stack.cairo
src/opcodes/tests/test_stack.cairo
src/stack.cairo

Implement OP_OVER & OP_2OVER opcodes

[feat] Implementation for OP_OVER & OP_2OVER opcodes 

---

src/stack.cairo

fix NOP 3DUP 1

---

src/errors.cairo
src/opcodes/arithmetic.cairo
src/scriptnum/scriptnum.cairo
src/scriptnum/tests/test_scriptnum.cairo
src/stack.cairo

fix: numequal bug

---

src/stack.cairo

fix: over_n bug

---

src/lib.cairo
src/main.cairo
src/tests/test_transactions.cairo
src/utxo.cairo
src/validate.cairo

feat: transaction validate function

---

frontend/src/app/globals.css
frontend/src/components/script-editor.tsx
frontend/src/components/stack-visualizer.tsx

Added text highlighting in debug mode so a user knows what op_code the debug data is for

Debug highlighting

---

Scarb.lock

bump ripemd160 library

---

src/compiler.cairo
src/engine.cairo
src/errors.cairo
src/opcodes/crypto.cairo
src/opcodes/opcodes.cairo
src/opcodes/tests/test_constants.cairo
src/opcodes/tests/test_disabled.cairo
src/opcodes/tests/test_stack.cairo
src/scriptflags.cairo
src/scriptnum/scriptnum.cairo
src/signature/sighash.cairo
src/signature/signature.cairo
src/signature/utils.cairo
src/stack.cairo
src/transaction.cairo
src/utils.cairo
src/validate.cairo
src/witness.cairo

- [✅] issue #207 
- [✅] follows contribution [guide](https://github.com/keep-starknet-strange/shinigami/blob/main/CONTRIBUTING.md)
- [✅] code change includes tests
Change all the posible 'while i < n' to 'while x != n'. The ones that were not changed generated certain errors in the tests
Closes #207

'while i < n' to 'while x != n' code optimization

---

Scarb.lock
packages/cmds/Scarb.toml
packages/cmds/src/main.cairo
packages/compiler/Scarb.toml
packages/compiler/src/compiler.cairo
packages/engine/Scarb.toml
packages/engine/src/engine.cairo
packages/engine/src/opcodes/constants.cairo
packages/engine/src/opcodes/crypto.cairo
packages/engine/src/opcodes/locktime.cairo
packages/engine/src/opcodes/opcodes.cairo
packages/engine/src/opcodes/stack.cairo
packages/engine/src/opcodes/tests/test_constants.cairo
packages/engine/src/opcodes/tests/test_crypto.cairo
packages/engine/src/opcodes/tests/utils.cairo
packages/engine/src/scriptflags.cairo
packages/engine/src/signature/sighash.cairo
packages/engine/src/signature/signature.cairo
packages/engine/src/signature/utils.cairo
packages/engine/src/stack.cairo
packages/engine/src/tests/test_coinbase.cairo
packages/engine/src/tests/test_p2pk.cairo
packages/engine/src/tests/test_p2pkh.cairo
packages/engine/src/tests/test_transactions.cairo
packages/engine/src/transaction.cairo
packages/engine/src/witness.cairo
packages/utils/Scarb.toml
tests/run-core-tests.sh

Dev: Raito compatability and integration

---

packages/engine/src/engine.cairo

fixes `["0x01 0x00","1","MINIMALDATA","OK"],`

fix: fix minimal data

---

packages/engine/src/engine.cairo
packages/engine/src/opcodes/crypto.cairo
packages/engine/src/opcodes/tests/test_disabled.cairo
packages/engine/src/scriptnum.cairo
packages/engine/src/signature/sighash.cairo
packages/engine/src/signature/signature.cairo
packages/engine/src/signature/utils.cairo
packages/engine/src/stack.cairo
packages/utils/src/byte_array.cairo

refac: refactor while I < data.len to let data_len = data.len()

---

packages/compiler/src/compiler.cairo
packages/engine/src/opcodes/opcodes.cairo

This PR will map the OP_NOP2 and OP_NOP3 in the compiler and add them to the OP codes list.

[feat] mapped OPNOP2 and OPNOP3

---

packages/cmds/src/main.cairo
packages/engine/src/engine.cairo
packages/engine/src/hash_cache.cairo
packages/engine/src/lib.cairo
packages/engine/src/opcodes/constants.cairo
packages/engine/src/opcodes/crypto.cairo
packages/engine/src/opcodes/flow.cairo
packages/engine/src/opcodes/locktime.cairo
packages/engine/src/opcodes/tests/utils.cairo
packages/engine/src/signature/sighash.cairo
packages/engine/src/signature/signature.cairo
packages/engine/src/signature/utils.cairo
packages/engine/src/tests/test_p2pk.cairo
packages/engine/src/tests/test_p2pkh.cairo
packages/engine/src/tests/test_transactions.cairo
packages/engine/src/validate.cairo

dev: Engine generic implementation

---

.github/PULL_REQUEST_TEMPLATE.md

It will automatically delete an issue if the PR is resolved.

Auto del issue once resolved

---

packages/engine/src/hash_tag.cairo
packages/engine/src/lib.cairo

Add the function [tagged_hash](https://github.com/btcsuite/btcd/blob/24eb815168f49dea84767817717a11bd7928eb23/chaincfg/chainhash/hash.go#L154)
This function is required for taproot especially [here](https://github.com/btcsuite/btcd/blob/24eb815168f49dea84767817717a11bd7928eb23/txscript/sighash.go#L601) and [here](https://github.com/btcsuite/btcd/blob/24eb815168f49dea84767817717a11bd7928eb23/btcec/schnorr/signature.go#L171)

feat: add bip340 hash tag

---

packages/engine/src/opcodes/crypto.cairo
packages/tests/src/tests/test_p2wsh.cairo

Fix multisig witness implementation

fix: multisig witness implementation

---

packages/cmds/src/main.cairo
scripts/get_tx_from_block.sh
scripts/run_bitcoin_transaction.sh

feat: modified bitcoin_transaction_script to infer flags
